[build]
  command = "node compile-data.js && npm install"
  functions = "netlify/functions"
  publish = "."

[functions]
  # This tells Netlify where the code is
  directory = "netlify/functions"
  node_bundle = true
  # We clear this out so Netlify stops hunting for the old broken library
  external_node_modules = []
